[package]
name = "samael"
version = "0.0.8"
authors = ["Nathan Jaremko <nathan@jaremko.ca>", "Alex Grinman <me@alexgr.in>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/njaremko/samael"
description = "A SAML2 library for Rust"
keywords = ["saml", "saml2", "xml", "sso"]
categories = ["authentication"]
build = "bindings.rs"

[features]
xmlsec = ["libc", "lazy_static", "libxml"]

[build-dependencies]
pkg-config =  "^0.3.17"
bindgen    = "0.59.1"

[dependencies]
base64 = "0.13"
chrono = { version = "0.4", features = ["serde"] }
data-encoding = "2.2.0"
derive_builder = "0.10.2"
flate2 = "1.0"
lazy_static = {version = "^1.4.0", optional = true}
libc        = {version = "^0.2.66", optional = true}
libxml = { version = "0.3.0", optional = true}
quick-xml = { version = "0.22.0", features = [ "serialize" ] }
rand = "0.8.4"
rsa = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.9"
snafu = "0.6"
url = "2.1.1"
uuid = { version = "0.8.1", features = ["v4"] }
x509-parser = "0.13.0"
